apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
      version: v1
  template:
    metadata:
      labels:
        app: currency-exchange
        version: v1
    spec:
      containers:
        - name: currency-exchange
          image: ravisankar/currency-exchange-devops:latest
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 8080