apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
    version: v1
  name: currency-exchange
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: currency-exchange
    version: v1
